# Write your MySQL query statement below
WITH HeavyDateStringification AS (
    SELECT 
        id,
        country,
        state,
        amount,
        -- THE CLUNKY TRAP: Casting to a string and chopping it instead of native DATE_FORMAT
        SUBSTRING(CAST(trans_date AS CHAR), 1, 7) AS month_str
    FROM Transactions
),
TotalTransactions AS (
    -- Pipeline 1: Grouping everything together
    SELECT 
        month_str,
        country,
        COUNT(id) AS trans_count,
        SUM(amount) AS trans_total_amount
    FROM HeavyDateStringification
    GROUP BY month_str, country
),
ApprovedTransactions AS (
    -- Pipeline 2: A completely separate grouping operation just for approved rows!
    SELECT 
        month_str,
        country,
        COUNT(id) AS approved_count,
        SUM(amount) AS approved_total_amount
    FROM HeavyDateStringification
    WHERE state = 'approved'
    GROUP BY month_str, country
)
-- Stitching the two massive temporary tables back together
SELECT 
    t.month_str AS month,
    t.country,
    t.trans_count,
    -- Safely catching the NULLs generated by our unnecessary table split
    COALESCE(a.approved_count, 0) AS approved_count,
    t.trans_total_amount,
    COALESCE(a.approved_total_amount, 0) AS approved_total_amount
FROM TotalTransactions t
LEFT JOIN ApprovedTransactions a 
    ON t.month_str = a.month_str 
    -- MySQL handles NULL = NULL automatically in some grouping, 
    -- but for joins we must explicitly map the NULL countries!
    AND (t.country = a.country OR (t.country IS NULL AND a.country IS NULL));